### ISSUE TITLE
"forced" option is not working

### ISSUE THREAD

**Issue by ma-zsola** [CogentRedTester/mpv-sub-select#11]
First of all, thank you for the great script.
It seems like, since your latest commits this setting is not working for me:
```
[ 
   {
        "alang": "hun?",
        "slang": [
            "forced",
            "no"
        ]
    }
]
```

The script cannot find the subtitle track with "forced" flag. I also tried it with "default" option and without the "no" option, but it doen't work either.
It works fine with other settings.

Can you help me?

**Comment by CogentRedTester** [comment]
Could you upload a log file generated with `--log-file` and with `--msg-level=sub_select='trace'`. Make sure that you open the file you're having trouble with so that it shows up in the log.

**Comment by ma-zsola** [comment]
My log: 
[log.txt](https://github.com/CogentRedTester/mpv-sub-select/files/9539892/log.txt)

**Comment by CogentRedTester** [comment]
Can you check if the latest commit fixed this for you?

**Comment by ma-zsola** [comment]
Yes, it"s working. :-)
Thank you very much.
