### ISSUE TITLE
Filter by subtitle format

### ISSUE THREAD

**Issue by rollingmoai** [CogentRedTester/mpv-sub-select#13]
How do I filter by subtitle format (`ass`, `pgs`, `srt`, `vtt`, etc...)?

**Comment by CogentRedTester** [comment]
You can use the new `condition` option.

This would only choose english ass subtitles to use with Japanese audio for example:

```json
    {
        "alang": "jpn?",
        "slang": "eng",
        "condition": "sub.codec == 'ass'"
    }
```

You can combine it with the `whitelist` `blacklist` properties as well. I have more details in the README. These conditions have the same syntax as [conditional profiles](https://mpv.io/manual/master/#conditional-auto-profiles) if you're already familiar with those. Just without all the magic property value stuff.

Just be aware that the codec value of a subtitle is not always the same as the file extension. For example I think that `srt` actually has a `subrip` codec.

**Comment by rollingmoai** [comment]
Thanks, it seems to work as expected
