### ISSUE TITLE
Allow optional preferred terms

### ISSUE THREAD

**Issue by SinTan1729** [CogentRedTester/mpv-sub-select#14]
In some files, there are more than one subtitle of the same language, and the subtitle with all the dialogues has a suffix `(full)`.  Is it possible to add it as an optional preferred term? Adding it as a whitelist term will select nothing when only one subtitle of that language is present.

**Comment by CogentRedTester** [comment]
Use multiple entries in the config file, give the first entry the whitelist items, and don't give them to the second. The script will then try to find a sub with the whitelist, and if it can't it'll fall back to the next entry.

**Comment by SinTan1729** [comment]
I tried that before, but I didn't put the whitelist as an array, now putting as an array worked.
