### ISSUE TITLE
[Question] Select by file name?

### ISSUE THREAD

**Issue by Obegg** [CogentRedTester/mpv-sub-select#23]
Example:
-- Folder name: Movie
--- Movie.mkv
--- Movie_eng.ass
--- Movie_chi.ass
--- Movie_spa.ass

Is it possible to auto-select subs with "eng" as their file name?
In some cases those are the only indications to which language the subs are.

**Comment by CogentRedTester** [comment]
This option here will select such external files if they do not contain a proper language code:

```json
    {
        "alang": "*",
        "slang": "und",
        "condition": "sub.external and (sub['external-filename'] or ''):lower():find('eng') ~= nil"
    }
```

**Comment by Obegg** [comment]
Thank you!
