### ISSUE TITLE
please help me configure it

### ISSUE THREAD

**Issue by AdventurerRussia** [CogentRedTester/mpv-sub-select#3]
did I put the setup file correctly? I didn't know exactly where
"C:\Program Files\MPV\mpv\script-opts\sub-select.json"

I watch anime, so here's how to make it so that the Japanese audio track selects the titles of the subtitles that I entered?
and can I make it so that an audio track with a specific name is selected, regardless of the title of the subtitles?
for example, I have an audio track from wakanim and crunchyroll in the video, how do I get the script to select crunchyroll? if it is 2 in the list?
I copied the settings file to different folders but the script doesn't work,

[
   
    {
        "alang": "*",
        "slang": ["*"],
        "blacklist": [ "Надписи" ]
    },
    {
        "alang": "*",
        "slang": "*",
        "whitelist": ["Полные"]
    }
    
]

**Comment by CogentRedTester** [comment]
Sorry, it seems I somehow completely missed this question, I didn't intend to ignore you. It's probably too late but I'll try to answer your question anyway.

On windows the `~~/script-opts/` directory is generally in `C:/Users/yourname/AppData/Roaming/mpv`.

The only ways to choose between subtitle tracks is using the language code or by using the titles of the tracks. You can see both of these things by middle muse clicking on the subtitle button on the OSC:

![mpv-shot0107](https://user-images.githubusercontent.com/57207260/169453212-46af75b8-d517-43c7-bf74-ac367970c68c.png)

The code inside the square brackets is the language code `eng` everything to the right of that is the title `Signs (SRT)`. `slang` chooses which language code you prefer and the `whitelist`/`blacklist` options are for filtering the titles. The example [sub-select.json](https://github.com/CogentRedTester/mpv-sub-select/blob/master/sub-select.json) file has a good preset that is designed to select the Japanese audio and English subtitles of many anime files.

I don't know how Crunchyroll and Wakanim title or code their tracks, but if they have a standard word in their titles you can use the `whitelist`/`blacklist` options to filter for it.

**Comment by SonaliBendre** [comment]
@CogentRedTester please provide a context menu

**Comment by CogentRedTester** [comment]
> @CogentRedTester please provide a context menu

A context menu to do what?

**Comment by crapvile** [comment]
Doesn't really seem to do anything for me. Placed the script in the ".lua" file in the scripts folder with the conf file and the json in "script-opts" and it still automatically picks the number 1 signs subtitle when it is configured to blacklist the one with that name. It's as if there is no script at all there. Is there some weird command I need to do for some reason to enable the script?
