### ISSUE TITLE
Add option to use "sid=" value from mpv.conf inside media folder

### ISSUE THREAD

**Issue by soredake** [CogentRedTester/mpv-sub-select#30]
MPV has useful option for overriding certain options per-folder by creating mpv.conf in it with option you need (for example `sid=2` to always select subtitle number two), but, sub-select overrides mpv's subtitle selecting logic and "sid" value from this file is not used, so, it would be nice to have an option to use "sid" value if mpv.conf has it.

**Comment by CogentRedTester** [comment]
Can you try the file from the commit referenced above.

**Comment by soredake** [comment]
Thank you! After switching to this branch and enabling `force_prediction` sid option is now respected in mpv.conf

**Comment by soredake** [comment]
@CogentRedTester shouldn't this be closed when [your commit](https://github.com/CogentRedTester/mpv-sub-select/commit/346abec563179b7dff6f48f15e89a16f9e18d3d9) will land to the master branch?
