### ISSUE TITLE
Would it be possible to compare subtitles with the video name instead?

### ISSUE THREAD

**Issue by xyz551** [CogentRedTester/mpv-sub-select#4]
I was wondering if it would be possible to compare the subtitles with the video name so that the correct sub for the episode could be used automatically. For example, E02 in the track title could be matched with the E02 subtitle if all the subs are loaded.

**Comment by CogentRedTester** [comment]
Why would one load all subtitles instead of letting mpv automatically load external subtitles that match the playing file?

**Comment by xyz551** [comment]
Usually the subtitle file names and the video file names don't match up with a tv series for example, so MPV wouldn't be able to load the correct subtitle unless I rename each and every subtitle file to match the video file. Currently I just load all the subtitles and cycle to the one for the episode since its a lot easier than renaming all the subtitle files, but was hoping if there was an easier solution.

**Comment by CogentRedTester** [comment]
This is really outside the scope of this project. The aim of this script is to choose what subtitle to use for the given audio, it is expected that all subtitles apply to the current video. Choosing to load subtitles that actually apply to that file is the job of mpv, the user, or another script. I don't want to over-complicate this script for such a niche use-case. Another script would be ideal, but I don't know of any that fit this specific use-case, and I'm too busy to write one myself.

You may want to look into the [fuzzy sub-auto option](https://mpv.io/manual/master/#options-sub-auto), which may be enough to fix the mismatch. There are also lots of [scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts) which allow you to download subtitles for the video online, which might bypass this problem altogether.
